import {CommercialProject} from "./Projects.types.ts";

export const commercialProjects: Array<CommercialProject> = [
    {
        title: "XYS",
        description: "TEST asdAOPSDIPOASID POASIDPOAISDOPi POAISDPOAISD oPIASDPOAISD opIASDPOIASOPD APOSIDAPSODI POAISDPOAISD pOAISDPOAISD AOPSDI APSODIASPODi  pOAISDPOAISD APSODIPAOSI dpoAISDPOIASPODIPAOISD PAOSIDPAOSIDPOi APSODIAPOSIDP PAOSIDPAOSIDPOi APSODIAPOSIDp PASODIAPOSIDPOI ASPDOIAPSODIPAOSID ASPODIAPOSIDPOASID PAOSDIPAOSID APSODIAPOSIDPOIASD APSOIDPOASIDPOAISD APSODIPAOSIDPOAISD APOSDIPOAISD APSODIPAOSID APSODIAPOSID ASPODIAPOSID",
        linkTitle: "http://wwww.test.com",
        linkSrc: "TOLOTOTLTOT"
    }
]